
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NucleoInformativo
 */
public class frmUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form frmUsuarios
     */
    Usuario usuarioActivo;
public static ConsultasBD consultasBD =new ConsultasBD();
    public frmUsuarios(Usuario u) {
        usuarioActivo=u;
        initComponents();
        setDefaultCloseOperation(0);
        
        
    }
    boolean admin=false;

    private frmUsuarios() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnEnviarMsg2 = new javax.swing.JButton();
        btnArtists = new javax.swing.JButton();
        btnEducation = new javax.swing.JButton();
        btnAnimals = new javax.swing.JButton();
        btnTravel = new javax.swing.JButton();
        btnWorld = new javax.swing.JButton();
        btnClothes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 0, 51));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("<html><center>Start<br/>Conversation<br/>witn the admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel1.setText("Select your category of game");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, 47));

        btnEnviarMsg2.setBackground(new java.awt.Color(51, 0, 51));
        btnEnviarMsg2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        btnEnviarMsg2.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarMsg2.setText("EXIT");
        btnEnviarMsg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMsg2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarMsg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, 36));

        btnArtists.setBackground(new java.awt.Color(255, 255, 255));
        btnArtists.setIcon(new javax.swing.ImageIcon(getClass().getResource("/218957f5d9f78bf1a65a56473d548925.jpg.png"))); // NOI18N
        btnArtists.setText("jButton2");
        btnArtists.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.pink, java.awt.Color.red));
        btnArtists.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtistsActionPerformed(evt);
            }
        });
        jPanel1.add(btnArtists, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 260, 200));

        btnEducation.setBackground(new java.awt.Color(255, 255, 255));
        btnEducation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graduation_cap.jpg.png"))); // NOI18N
        btnEducation.setText("jButton2");
        btnEducation.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.pink, java.awt.Color.red));
        btnEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEducationActionPerformed(evt);
            }
        });
        jPanel1.add(btnEducation, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, 200));

        btnAnimals.setBackground(new java.awt.Color(255, 255, 255));
        btnAnimals.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo.png"))); // NOI18N
        btnAnimals.setText("jButton2");
        btnAnimals.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.pink, java.awt.Color.red));
        btnAnimals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimalsActionPerformed(evt);
            }
        });
        jPanel1.add(btnAnimals, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 260, 200));

        btnTravel.setBackground(new java.awt.Color(255, 255, 255));
        btnTravel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tnegg-logo1.png"))); // NOI18N
        btnTravel.setText("jButton2");
        btnTravel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.pink, java.awt.Color.red));
        btnTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelActionPerformed(evt);
            }
        });
        jPanel1.add(btnTravel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 260, 200));

        btnWorld.setBackground(new java.awt.Color(255, 255, 255));
        btnWorld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Capitales-del-mundo-logo-quiz-128x128.jpg.png"))); // NOI18N
        btnWorld.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.pink, java.awt.Color.red));
        btnWorld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorldActionPerformed(evt);
            }
        });
        jPanel1.add(btnWorld, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 260, 200));

        btnClothes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ropa_318-98542.jpg"))); // NOI18N
        btnClothes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.pink, java.awt.Color.red));
        btnClothes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClothesActionPerformed(evt);
            }
        });
        jPanel1.add(btnClothes, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 260, 200));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel2.setText("Travel");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel3.setText("Education");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel4.setText("Animals");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel5.setText("World");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("Clothes");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel7.setText("Artists");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 866, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(admin){
            JOptionPane.showMessageDialog(this, "Un administrador no se puede enviar mensajes a si mismo, solo los usuarios lo pueden hacer ");
        }else{
        frmMsgAdmin msg=new frmMsgAdmin(usuarioActivo);
        msg.setVisible(true);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEnviarMsg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMsg2ActionPerformed
        System.exit(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarMsg2ActionPerformed

    private void btnEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEducationActionPerformed
        Levels l=new Levels(usuarioActivo,"EDUCATION");
        l.setVisible(true);
        this.setVisible(false);
            // TODO add your handling code here:
    }//GEN-LAST:event_btnEducationActionPerformed

    private void btnAnimalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimalsActionPerformed
 Levels l=new Levels(usuarioActivo,"ANIMALS");
        l.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnimalsActionPerformed

    private void btnTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelActionPerformed
 Levels l=new Levels(usuarioActivo,"TRAVEL");
        l.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTravelActionPerformed

    private void btnWorldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorldActionPerformed
 Levels l=new Levels(usuarioActivo,"WORLD");
        l.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnWorldActionPerformed

    private void btnClothesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClothesActionPerformed
 Levels l=new Levels(usuarioActivo,"CLOTHES");
        l.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnClothesActionPerformed

    private void btnArtistsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistsActionPerformed
 Levels l=new Levels(usuarioActivo,"ARTISTS");
        l.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnArtistsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnimals;
    private javax.swing.JButton btnArtists;
    private javax.swing.JButton btnClothes;
    private javax.swing.JButton btnEducation;
    private javax.swing.JButton btnEnviarMsg2;
    private javax.swing.JButton btnTravel;
    private javax.swing.JButton btnWorld;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
