/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NucleoInformativo
 */
import javax.swing.JOptionPane;
 import java.util.Random;

public class Levels extends javax.swing.JFrame {

    /**
     * Creates new form Levels
     */
    Juego usuarioActivo;
   public static ConsultasBD consultasBD =new ConsultasBD();
    public Levels(Usuario u,String cat) {
        initComponents();
        javax.swing.JButton[] boton={jButton1,jButton2,jButton3,jButton4,jButton5,jButton6,jButton7,jButton8};
        
        //usuarioActivo=new Juego(cat, "", "", "", u);
        usuarioActivo= consultasBD.obtenerJuegousuario(u.getId_usuario(), cat, u);
        
        int level=Integer.parseInt(usuarioActivo.getLevel());
        
            if(level<=7){
                
                for(int i=7;i>level-1;i--){
                boton[i].setVisible(false);
                }
            }
        setDefaultCloseOperation(0);
        txtShowMain.setText("<html>Welcome "+""+u.getNombre()+" "+u.getApellido()+""+"<br> START A NEW LEVEL: ");
    }

    private Levels() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtShowMain = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnEnviarMsg2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtShowMain.setFont(new java.awt.Font("Tekton Pro Ext", 1, 36)); // NOI18N
        txtShowMain.setForeground(new java.awt.Color(255, 255, 255));
        txtShowMain.setText("Welcome student, up a level");
        jPanel1.add(txtShowMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton1.setText("L. 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 210, 100));

        jButton2.setBackground(new java.awt.Color(51, 255, 51));
        jButton2.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton2.setText("L. 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 210, 100));

        jButton3.setBackground(new java.awt.Color(51, 255, 51));
        jButton3.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton3.setText("L.3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 210, 100));

        jButton4.setBackground(new java.awt.Color(51, 255, 51));
        jButton4.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton4.setText("L. 4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 140, 210, 100));

        jButton5.setBackground(new java.awt.Color(51, 255, 51));
        jButton5.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton5.setText("L. 5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 210, 100));

        jButton6.setBackground(new java.awt.Color(51, 255, 51));
        jButton6.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton6.setText("L. 6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 210, 100));

        jButton7.setBackground(new java.awt.Color(51, 255, 51));
        jButton7.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton7.setText("L. 7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 330, 210, 100));

        jButton8.setBackground(new java.awt.Color(51, 255, 51));
        jButton8.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jButton8.setText("L. 8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 210, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamea.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 20, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/regresar.jpg"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, -1));

        jButton10.setBackground(new java.awt.Color(51, 0, 51));
        jButton10.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("<html><center>Start<br/>Conversation<br/>witn the admin");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        btnEnviarMsg2.setBackground(new java.awt.Color(51, 0, 51));
        btnEnviarMsg2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        btnEnviarMsg2.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviarMsg2.setText("EXIT");
        btnEnviarMsg2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarMsg2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnviarMsg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1041, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Random rnd = new Random();
        int numero=(int)(rnd.nextDouble() * 2 + 1);
        if(numero==1){
        frmPreguntas p=new frmPreguntas(usuarioActivo,7);
        p.setVisible(true);
        this.setVisible(false);
        }else{
            Memorama m=new Memorama(usuarioActivo,7);
            m.setVisible(true);
            this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Random rnd = new Random();
        int numero=(int)(rnd.nextDouble() * 2 + 1);
        if(numero==1){
        frmPreguntas p=new frmPreguntas(usuarioActivo,5);
        p.setVisible(true);
        this.setVisible(false);
        }else{
            Memorama m=new Memorama(usuarioActivo,5);
            m.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        frmUsuarios f=new frmUsuarios(usuarioActivo);
        f.setVisible(true);
        this.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
boolean admin=false;
        if(admin){
            JOptionPane.showMessageDialog(this, "Un administrador no se puede enviar mensajes a si mismo, solo los usuarios lo pueden hacer ");
        }else{
            frmMsgAdmin msg=new frmMsgAdmin(usuarioActivo);
            msg.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void btnEnviarMsg2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarMsg2ActionPerformed
        System.exit(1);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarMsg2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Random rnd = new Random();
        int numero=(int)(rnd.nextDouble() * 2 + 1);
        if(numero==1){
        frmPreguntas p=new frmPreguntas(usuarioActivo,1);
        p.setVisible(true);
        this.setVisible(false);
        }else{
            Memorama m=new Memorama(usuarioActivo,1);
            m.setVisible(true);
            this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Random rnd = new Random();
        int numero=(int)(rnd.nextDouble() * 2 + 1);
        if(numero==1){
        frmPreguntas p=new frmPreguntas(usuarioActivo,2);
        p.setVisible(true);
        this.setVisible(false);
        }else{
            Memorama m=new Memorama(usuarioActivo,2);
            m.setVisible(true);
            this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Random rnd = new Random();
        int numero=(int)(rnd.nextDouble() * 2 + 1);
        if(numero==1){
        frmPreguntas p=new frmPreguntas(usuarioActivo,3);
        p.setVisible(true);
        this.setVisible(false);
        }else{
            Memorama m=new Memorama(usuarioActivo,3);
            m.setVisible(true);
            this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Random rnd = new Random();
        int numero=(int)(rnd.nextDouble() * 2 + 1);
        if(numero==1){
        frmPreguntas p=new frmPreguntas(usuarioActivo,4);
        p.setVisible(true);
        this.setVisible(false);
        }else{
            Memorama m=new Memorama(usuarioActivo,4);
            m.setVisible(true);
            this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Random rnd = new Random();
        int numero=(int)(rnd.nextDouble() * 2 + 1);
        if(numero==1){
        frmPreguntas p=new frmPreguntas(usuarioActivo,8);
        p.setVisible(true);
        this.setVisible(false);
        }else{
            Memorama m=new Memorama(usuarioActivo,8);
            m.setVisible(true);
            this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Random rnd = new Random();
        int numero=(int)(rnd.nextDouble() * 2 + 1);
        if(numero==1){
        frmPreguntas p=new frmPreguntas(usuarioActivo,6);
        p.setVisible(true);
        this.setVisible(false);
        }else{
            Memorama m=new Memorama(usuarioActivo,6);
            m.setVisible(true);
            this.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Levels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Levels().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviarMsg2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtShowMain;
    // End of variables declaration//GEN-END:variables
}
